plugins:
  - rubocop-rake
  - rubocop-rspec


Layout/LineLength:
  Max: 140

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false


Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 50


Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
