plugins:
  - rubocop-rake
  - rubocop-rspec


AllCops:
  NewCops: enable


Gemspec/RequiredRubyVersion:
  Enabled: false


Layout/LineLength:
  Max: 140

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false


Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 55

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 18


Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
